### PR TITLE
further copy / delete sheet support

### PR DESCRIPTION
**Pull request by yenesey**

### CODE REVIEW

**Comment by kant2002** [comment]
@SkyKilla there small issues with test suite. Could take a look why build is failing.
I fix optilude's test suite, to dont fail, but after your PR it is again failing.

**Comment by yenesey** [comment]
Fixed, 
...but now have some problems with multiple pages with identical placeholders in
    Workbook.prototype.substituteScalar
Leave "TODO" message there

**Comment by kant2002** [comment]
Could you file new issue, about that.
I think I have idea what exactly you mean, but if you attach template to illustrate proble + small data which show the problem, then it would be easier to fix.

**Comment by yenesey** [comment]
Here is an example (2 sheets)

**Comment by kant2002** [comment]
@SkyKilla still does not get them. Send on email in the profile

**Comment by yenesey** [comment]
Ok. Example just sent.

**Comment by yenesey** [comment]
Hello!
Send files from my google mail about 8 days ago.
Confirm receiving please.

**Comment by kant2002** [comment]
@SkyKilla could you resubmit PR against original repo ?

**Comment by yenesey** [comment]
already done (if you mean  optilude/xlsx-template ?)

**Pull request closed without merging**
